49986 : Badges display on session expired.
exoplatform/exo-ios pull request #130
Opened 2021-10-14 16:45 UTC by wbenabdessalem

iOS_Session_expired_US01:  Badges display on session expired.

2021-10-14 18:51 UTC, ahamdi requested changes

2021-10-14 18:51 UTC, ahamdi commented on eXo/Sources/Controllers/ConnectToExoVC/ConnectToExoViewController.swift
> +        if let _quitTimestamp = defaults.value(forKey: "quitTimestamp") as? Double {
This is not a valid check for session timeout. The best will be to use this URL to get the user status https://url.of.exo/portal/rest/state/status/${userName}
could you use this to check the user connectivity ?

2021-10-14 18:52 UTC, ahamdi commented on eXo/Sources/Controllers/ConnectToExoVC/ConnectToExoViewController.swift
> +            if (Date().timeIntervalSince1970 - _quitTimestamp) > eXoAppDelegate.sessionTimeout  {
eXoAppDelegate.sessionTimeout is not a right value for session timeout, we need to remove it completely

2021-10-19 13:48 UTC, wbenabdessalem commented on eXo/Sources/Controllers/ConnectToExoVC/ConnectToExoViewController.swift
> +        if let _quitTimestamp = defaults.value(forKey: "quitTimestamp") as? Double {
This link is not accessible through the web

2021-10-20 10:53 UTC, wbenabdessalem commented on eXo/Sources/Controllers/ConnectToExoVC/ConnectToExoViewController.swift
> +            if (Date().timeIntervalSince1970 - _quitTimestamp) > eXoAppDelegate.sessionTimeout  {
Done ; with new check through the remote url

2021-10-20 11:17 UTC, closed without merging