45197 : AddingURL_US_05
exoplatform/exo-ios pull request #56
Opened 2021-06-20 21:42 UTC by wbenabdessalem

Given i am a user mobile
When iam on add your exo screen
Then i want to have next icon in front of input URL

2021-06-21 12:08 UTC, ahamdi requested changes

2021-06-21 12:08 UTC, ahamdi commented on eXo/eXo.entitlements
> +		<string>group.org.exoplatform.exo-snapshot</string>
This change should not be added here, it is related to the commit added by @hbenali for branch creation.
Couldn't we still use group.$(APP_BUNDLE_ID)

2021-06-22 14:53 UTC, wbenabdessalem reviewed
update groupe <string>group.$(APP_BUNDLE_ID)</string>

2021-06-22 15:02 UTC, ahamdi requested changes

2021-06-22 15:19 UTC, wbenabdessalem reviewed
Update AppDelegate

2021-06-22 21:04 UTC, ahamdi approved these changes

2021-06-23 00:09 UTC, merged